-- V1 : schéma initial — conforme au diagramme D2 du cahier des charges
-- Les tables métier (presences, exercices, relectures) arrivent avec leurs tickets T3, T4, T6.

CREATE TABLE promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

CREATE TABLE etudiant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL,
    nom VARCHAR(100) NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

CREATE TABLE session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT NOT NULL,
    titre VARCHAR(200) NOT NULL,
    code VARCHAR(10) NOT NULL,
    ouverture_at TIMESTAMP NOT NULL,
    expiration_at TIMESTAMP NOT NULL,  -- RG1 : ouverture + 15 min
    cloture_at TIMESTAMP,              -- nullable : NULL = session ouverte (RG12)
    CONSTRAINT uk_session_code UNIQUE (code),
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);
