-- V3 : présences (RG2 : unicité session+étudiant) et suivi des tentatives de code (RG3/RG4)

CREATE TABLE presence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    source VARCHAR(20) NOT NULL,
    marque_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR'))
);

-- RG4 : compteur d'échecs consécutifs (code inconnu ou expiré) et blocage 2 minutes.
-- Un seul suivi par étudiant : avec un code inconnu, la session visée est par
-- définition inconnue — le blocage porte sur l'étudiant, ce qui est plus strict
-- et conforme à l'intention anti-dévination de Q4.
CREATE TABLE tentative_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etudiant_id BIGINT NOT NULL,
    echecs_consicutifs INT NOT NULL DEFAULT 0,
    bloque_jusqua TIMESTAMP,
    CONSTRAINT uk_tentative_etudiant UNIQUE (etudiant_id)
);
