-- V5 : exercices déposés (RG5 : un seul exercice par étudiant et par session).
-- Les statuts sont ceux du contrat et du diagramme D4 :
-- depose -> en_attente_relecteur | assigne -> relu

CREATE TABLE exercice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    lien VARCHAR(500) NOT NULL,
    statut VARCHAR(30) NOT NULL,
    depose_at TIMESTAMP NOT NULL,
    maj_at TIMESTAMP,
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session (id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id),
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('depose', 'en_attente_relecteur', 'assigne', 'relu'))
);
