-- V6 : relectures (RG16 : un seul relecteur par exercice — unique(exercice_id)).
-- Le relecteur est un étudiant présent à la session, différent de l'auteur (RG13, RG7).
-- statut : assignee -> rendue. Une relecture rendue est définitive (RG10, Q15).

CREATE TABLE relecture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id BIGINT NOT NULL,
    relecteur_id BIGINT NOT NULL,
    statut VARCHAR(20) NOT NULL,
    note INT,
    commentaire VARCHAR(2000),
    assignee_at TIMESTAMP NOT NULL,
    rendue_at TIMESTAMP,
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),
    CONSTRAINT ck_relecture_statut CHECK (statut IN ('assignee', 'rendue')),
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR (note >= 0 AND note <= 20)),
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id)
);
